/*
  # Update emp_id to auto-incrementing bigint

  1. Changes
    - Convert emp_id column to BIGINT type
    - Set emp_id as auto-incrementing (GENERATED BY DEFAULT AS IDENTITY)
    - Ensure emp_id remains the primary key

  2. Notes
    - This will make emp_id automatically increment starting from 1
    - Existing data will be preserved with new sequential IDs
*/

-- First, create a temporary sequence to handle existing data
CREATE SEQUENCE IF NOT EXISTS temp_emp_id_seq START 1;

-- Update existing emp_id values to be sequential starting from 1
UPDATE erms.employee 
SET emp_id = nextval('temp_emp_id_seq')
WHERE emp_id IS NOT NULL;

-- Drop the temporary sequence
DROP SEQUENCE IF EXISTS temp_emp_id_seq;

-- Alter the emp_id column to be BIGINT and auto-incrementing
ALTER TABLE erms.employee 
ALTER COLUMN emp_id TYPE BIGINT,
ALTER COLUMN emp_id SET DEFAULT nextval('erms.employee_emp_id_seq'::regclass);

-- Create or replace the sequence for emp_id
CREATE SEQUENCE IF NOT EXISTS erms.employee_emp_id_seq 
OWNED BY erms.employee.emp_id;

-- Set the sequence to start from the next available number
SELECT setval('erms.employee_emp_id_seq', COALESCE(MAX(emp_id), 0) + 1, false) 
FROM erms.employee;

-- Make emp_id generated by default as identity
ALTER TABLE erms.employee 
ALTER COLUMN emp_id SET DEFAULT nextval('erms.employee_emp_id_seq'::regclass);