/*
  # Update employee_id to auto-incrementing bigint

  1. Changes
    - Convert employee_id column to BIGINT type
    - Set employee_id as auto-incrementing (GENERATED BY DEFAULT AS IDENTITY)
    - Ensure employee_id remains the primary key

  2. Notes
    - This will make employee_id automatically increment starting from 1
    - Existing data will be preserved with new sequential IDs
*/

-- First, create a temporary sequence to handle existing data
CREATE SEQUENCE IF NOT EXISTS temp_employee_id_seq START 1;

-- Update existing employee_id values to be sequential starting from 1
UPDATE erms.employee 
SET employee_id = nextval('temp_employee_id_seq')
WHERE employee_id IS NOT NULL;

-- Drop the temporary sequence
DROP SEQUENCE IF EXISTS temp_employee_id_seq;

-- Alter the employee_id column to be BIGINT and auto-incrementing
ALTER TABLE erms.employee 
ALTER COLUMN employee_id TYPE BIGINT,
ALTER COLUMN employee_id SET DEFAULT nextval('erms.employee_employee_id_seq'::regclass);

-- Create or replace the sequence for employee_id
CREATE SEQUENCE IF NOT EXISTS erms.employee_employee_id_seq 
OWNED BY erms.employee.employee_id;

-- Set the sequence to start from the next available number
SELECT setval('erms.employee_employee_id_seq', COALESCE(MAX(employee_id), 0) + 1, false) 
FROM erms.employee;

-- Make employee_id generated by default as identity
ALTER TABLE erms.employee 
ALTER COLUMN employee_id SET DEFAULT nextval('erms.employee_employee_id_seq'::regclass);